spring:
  application:
    name: anime-service
  threads:
    virtual:
      enabled: true


server:
  servlet:
    context-path: /${spring.application.name}
  error:
    include-stacktrace: ON_PARAM
  tomcat:
    threads:
      max: 20
